image: Visual Studio 2017

matrix:
  fast_finish: true

platform:
  - x64
  - x86

clone_folder: c:\projects\Allocators

environment:
  matrix:
    - TOOLCHAIN: msvc15
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017

build_script:
  - cd c:\projects\Allocators
  - if "%platform%" equ "x86" (cmake CMakeLists.txt -G "Visual Studio 15 2017")
  - if "%platform%" equ "x64" (cmake CMakeLists.txt -G "Visual Studio 15 2017 Win64")
  - if "%platform%" equ "x86" (msbuild /m /p:Configuration=Release /p:Platform="Win32" Allocators.sln)
  - if "%platform%" equ "x64" (msbuild /m /p:Configuration=Release /p:Platform="x64"   Allocators.sln)
  - if "%platform%" equ "x86" (msbuild /m /p:Configuration=Debug   /p:Platform="Win32" Allocators.sln)
  - if "%platform%" equ "x64" (msbuild /m /p:Configuration=Debug   /p:Platform="x64"   Allocators.sln)